source 'https://rubygems.org'
gem 'github-pages'
gem 'rouge', '1.6.2'
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
# gem 'pygments'
# gem 'redcarpet'
# gem 'jekyll-watch'
# gem 'fast-stemmer'
